# SPDX-FileCopyrightText: 2026 Afcoo
# SPDX-License-Identifier: GPL-2.0-or-later

[server]
host-name=thrurndis
domain-name=local
use-ipv4=yes
use-ipv6=no
allow-interfaces=usb0
use-iff-running=yes
enable-dbus=no

[wide-area]
enable-wide-area=no

[publish]
publish-addresses=yes
publish-hinfo=no
publish-workstation=no
publish-domain=no
publish-resolv-conf-dns-servers=no
publish-a-on-ipv6=no
publish-aaaa-on-ipv4=no
disable-user-service-publishing=yes

[reflector]
enable-reflector=no
